version: '3.7' 
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Ruta al Dockerfile
    ports:
      - "8080:80"
    
  db:
    image: mysql:8.0
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'sample'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'sampleuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'c'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'samplepass'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
volumes:
    web_data:
    my-db:
